// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxgNX8-Mx2jKr2Tsq8pKG-Sp7tH8i7kb4',
    appId: '1:635822590769:web:389cef9f93ba2d44bfbe10',
    messagingSenderId: '635822590769',
    projectId: 'eterna-b2afd',
    authDomain: 'eterna-b2afd.firebaseapp.com',
    storageBucket: 'eterna-b2afd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClRafyo1V8vXYQjhK2CqgQgi_L-DTGths',
    appId: '1:635822590769:android:00208f085241eef5bfbe10',
    messagingSenderId: '635822590769',
    projectId: 'eterna-b2afd',
    storageBucket: 'eterna-b2afd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZtRH_FUP4zKgW55O-rCKWYSsaciVTTkM',
    appId: '1:635822590769:ios:4011a810f4577cf5bfbe10',
    messagingSenderId: '635822590769',
    projectId: 'eterna-b2afd',
    storageBucket: 'eterna-b2afd.firebasestorage.app',
    iosBundleId: 'com.example.run',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZtRH_FUP4zKgW55O-rCKWYSsaciVTTkM',
    appId: '1:635822590769:ios:4011a810f4577cf5bfbe10',
    messagingSenderId: '635822590769',
    projectId: 'eterna-b2afd',
    storageBucket: 'eterna-b2afd.firebasestorage.app',
    iosBundleId: 'com.example.run',
  );
}
